name: Azure GitHub Analytics ETL Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 3 * * 1' # Se ejecuta cada Lunes a las 3 AM UTC

jobs:
  etl-only:
    name: 'Run Python ETL Script'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install ODBC Driver for SQL Server
      run: |
        sudo apt-get update
        sudo apt-get install -y unixodbc-dev
        curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --batch --yes --dearmor -o /usr/share/keyrings/microsoft-prod.gpg
        curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
        sudo apt-get update
        sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ETL script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DB_SERVER: sql-upt-tech-analysis-server-lsnvfq.database.windows.net
        DB_DATABASE: db-upt-tech-analysis
        DB_USERNAME: dbadmin885
        DB_PASSWORD: sY7CB!D5$BuzCov3
      run: python ./scrap_pequeno.py
