name: Deploy Infrastructure

on:
  workflow_dispatch: # Permite ejecutar manualmente
  push:
    branches:
      - main
    paths:
      - 'infra/**'

jobs:
  deploy-infrastructure:
    name: 'Deploy Azure Infrastructure'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./infra

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: 'Login to Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Setup backend (create storage if needed)
      run: |
        # Verificar si existe el storage account para el backend
        if ! az storage account show --name stterraformstatelsnvfq --resource-group rg-upt-tech-analysis-lsnvfq >/dev/null 2>&1; then
          echo "Creating backend storage..."
          az group create --name rg-upt-tech-analysis-lsnvfq --location "West US 2" || true
          az storage account create \
            --resource-group rg-upt-tech-analysis-lsnvfq \
            --name stterraformstatelsnvfq \
            --sku Standard_LRS \
            --encryption-services blob
          az storage container create \
            --name tfstate \
            --account-name stterraformstatelsnvfq
        fi

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan

    - name: Display Terraform Outputs
      run: |
        echo "=== Terraform Outputs ==="
        terraform output
